name: Deploy to Bunny Storage
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Install rclone
        run: sudo apt-get install -y rclone

      - name: Configure rclone for Bunny
        run: |
          mkdir -p ~/.config/rclone
          echo "[bunny]
          type = ftp
          host = storage.bunnycdn.com
          user = ${{ secrets.BUNNY_STORAGE_USERNAME }}
          pass = ${{ secrets.BUNNY_STORAGE_PASSWORD }}" > ~/.config/rclone/rclone.conf

      - name: Upload dist folder to Bunny Storage
        run: |
          rclone sync ./dist bunny:${{ secrets.BUNNY_STORAGE_ZONE_NAME }} --progress --exclude ".*"

      - name: Purge Bunny CDN cache (optional)
        run: |
          curl -X POST "https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULLZONE_ID }}/purgeCache" \
          -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}" \
          -H "Accept: application/json"
