name: Deploy to Bunny CDN
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Install rclone
        run: sudo apt-get install -y rclone

      - name: Configure rclone for Bunny
        run: |
          mkdir -p ~/.config/rclone
          echo "[bunny-site]
          type = ftp
          host = storage.bunnycdn.com
          user = ${{ secrets.BUNNY_SITE_USERNAME }}
          pass = PASS_PLAIN:$(echo ${{ secrets.BUNNY_SITE_PASSWORD }} | base64)

          [bunny-media]
          type = ftp
          host = storage.bunnycdn.com
          user = ${BUNNY_MEDIA_USERNAME}
          pass = PASS_PLAIN:${BUNNY_MEDIA_PASSWORD}" > ~/.config/rclone/rclone.conf
        env:
          BUNNY_SITE_USERNAME: ${{ secrets.BUNNY_SITE_USERNAME }}
          BUNNY_SITE_PASSWORD: ${{ secrets.BUNNY_SITE_PASSWORD }}
          BUNNY_MEDIA_USERNAME: ${{ secrets.BUNNY_MEDIA_USERNAME }}
          BUNNY_MEDIA_PASSWORD: ${{ secrets.BUNNY_MEDIA_PASSWORD }}

      # 🚀 Deploy site (exclude images/videos)
      - name: Deploy site files to HDD storage
        run: |
          echo "🚀 Uploading site (excluding media)..."
          rclone sync ./dist bunny-site:${{ secrets.BUNNY_SITE_ZONE_NAME }} \
            --progress \
            --exclude "/images/**" \
            --exclude "/videos/**" \
            --exclude ".*"

      # 🎞 Deploy images/videos separately
      - name: Deploy media files to SSD storage
        run: |
          echo "🎞 Uploading media..."
          if [ -d "./dist/videos" ]; then
            rclone sync ./dist/videos bunny-media:${{ secrets.BUNNY_MEDIA_ZONE_NAME }}/videos --progress --exclude ".*"
          fi
          if [ -d "./dist/images" ]; then
            rclone sync ./dist/images bunny-media:${{ secrets.BUNNY_MEDIA_ZONE_NAME }}/images --progress --exclude ".*"
          fi

      # 🧹 Purge CDN cache
      - name: Purge Bunny CDN cache
        run: |
          echo "🧹 Purging CDN cache..."
          curl -X POST "https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULLZONE_ID }}/purgeCache" \
            -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}" \
            -H "Accept: application/json"
